### ISSUE TITLE
Integrate with coveralls marketplace app

### ISSUE THREAD

**Issue by mdabrowski1990** [mdabrowski1990/uds#99]
## Description
As a developer, I would like to have coveralls integrated via app instead of manual CI configuration, so I have more features and easier to understand github workflow.

Documentation: https://github.com/marketplace/actions/coveralls-github-action

## Acceptance Criteria
- coveralls intergrated with the project

**Comment by mdabrowski1990** [comment]
It seems that coverall app uses `lcov` file while our output is '.coverage'.
I was not able to configure it, this is a job I have creted:
```
  test_coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Step up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          pip install -r requirements.txt

      - name: Install external packages used for dynamic tests
        run: |
          pip install -r tests/requirements_for_software_tests.txt

      - name: Execute software tests [pytest]
        run: |
          coverage run --source=uds -m pytest tests/software_tests/

      - name: Assess code coverage [coveralls]
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: .coverage
          flag-name: software
```

I abandon the task
